### PR TITLE
Remove pkg.yml and adjust versioning logic

### LINKED ISSUE #5: Replace pkg.yml with workflow variables
**What would you like to be added**:
Currently, configuration parameter regarding the package build are defined in the `pkg.yml` file within each package repo. On one hand, it allows to define package build parameters from the root directory but on the other hand it also adds redundancy because most of the information is similar between multiple package builds. Further, some information could be even gathered during runtime (e.g. verison).

As a result, I suggest to get rid of the `pkg.yml` file and use input variables of Github Action workflows to define a proper interface and use default values for the most common parameters like:
* email
* name
* distribution
* message

**Why is this needed**:
This minimizes redundancy by defining proper defaults between package builds.

### PR DESCRIPTION
**Pull request by nanory**
**What this PR does / why we need it**:
This PR gets rid of the `pkg.yml` and ensures that the Git Tag of a project determines the version of the package. Otherwise, the Git commit hash is taken

**Which issue(s) this PR fixes**:
Fixes #5

### CODE REVIEW

**Comment by ghost** [comment]
@nanory Thank you for your contribution.

**Comment by alee-cd** [comment]
Tested this workflow changes works with `apt_source`, `git_source` and also `native` three different type of packages:
https://github.com/gardenlinux/package-htop/actions/runs/6983646731
https://github.com/gardenlinux/package-iproute2/actions/runs/7003594089
https://github.com/gardenlinux/package-iproute2/actions/runs/7004046530

I think we may now drop the hardcoded `ref: feature/5-remove-pkg-yml` and merge.

**Review by alee-cd — APPROVED** [review]

**Comment by alee-cd** [comment]
I'm now dropping the hardcoded `ref: feature/5-remove-pkg-yml ` line. Ready for merge,.

**Comment by alee-cd** [comment]
I started to migrate package-`systemd`, and I found we can optimize the `build.yml` by use:
```
jobs:
  build_pkg:
    uses: gardenlinux/package-build/.github/workflows/build_pkg.yml@main
```
So that we don’t need `--arg name "$name" '.jobs[$name]`. in the `yq` command in `build_source` script.
So that all the`build.yml` files from other package-* will be only has difference on the first line with name, eg:
```
name: systemd
```
I will adjust the workflow in this PR.

**Pull request merged**
